config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
belongs_to :user    
validates :title, presence:true, uniqueness:true, length:{minimum:3,maximum:26}
validates :description, presence:true ,uniqueness:true, length:{minimum:5,maximum:100}

end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :articles
    validates :username, presence: true,uniqueness: {case_sensitive: false}, length: {minmum:3,maximum:26}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:1000},
                        uniqueness: {case_sensitive: false},
                        format: {with: VALID_EMAIL_REGEX }
    has_secure_password   
    validates :password, presence: true          
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article=Article.find(params[:id])
  end
  def index
    @articles=Article.all
  end
  def new
    @article=Article.new()
  end

  def edit
    @article=Article.find(params[:id])
  end

  def create
    @article=Article.new(params.require(:article).permit(:title,:description))
    @article.user=User.first
    if @article.save
        flash[:notice]="article was created successfully"
        redirect_to @article
    else
        render 'new'
    end
  end

  def update
    @article=Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
        flash[:notice]="Article was updated successfully"
        redirect_to @article
    else
        render 'edit'
    end
  end

  def destroy
    @article=Article.find(params[:id])
    @article.destroy
    flash[:notice]="Article was deleted successfull"
    redirect_to articles_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
  def about

  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new 

end

def create
    
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end
  

def destroy
    session[:user_id]=nil
    flash[:notice]="logged out successfully"
    redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user=User.find(params[:id])
        @articles=@user.articles
    end

    def index
        @users=User.all

    end
    def new
        @user=User.new()
    end

    def edit
        @user=User.find(params[:id])
    end
    def create
        @user=User.new( params.require(:user).permit(:username, :email, :password))
        if @user.save
            flash[:notice]="User created successfully"
            redirect_to articles_path
        else
            render 'new'

        end
    end

    def update
        @user=User.find(params[:id])
        if @user.update(params.require(:user).permit(:username, :email, :password))
            flash[:notice]="User updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/views/articles/_form.html.erb
<div class="row justify-content-center">
<div class="col-10">
<% if @article.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved</h4>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> 
  <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
    <div class="form-group row">
      <%= f.label :title, class: "col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
      </div>
    </div>
    <div class="form-group row">
    <%= f.label :description, class: "col-2 col-form-label text-light" %>
    <div class="col-10"> 
      <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
    </div>
  </div>
  <div class="form-group row justify-content-center">
  <%= f.submit class: "btn btn-outline-light btn-lg" %>
</div>
<% end %>
</div>
<%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
</div>
</div> 

app/views/articles/_list.html.erb
<div class="container card-width ">
<% @articles.each do |article| %>
<div class="card text-center mb-4">

  <div class="card-header">
    by <%= article.user.username if article.user %>
  </div>
  <div class="card-body">
 
    <h5 class="card-title "><%= article.title %></h5>
    <p class="card-text"><%= article.description %></p>
    <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
    <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
    
  </div>
  <div class="card-footer text-muted ">
   <p> Created: <%= time_ago_in_words(article.created_at) %> ago  Updated: <%= time_ago_in_words(article.updated_at) %> ago</p>
   
  </div>
 
</div>
<% end %>

app/views/articles/edit.html.erb
<div id="page-content">
<h2>Edit the article</h2>

<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div id="page-content">

<h1>Article indexing page</h1>
<%= render 'list' %>

</div>
</div>

app/views/articles/new.html.erb
<h1>Create new article</h1>
<h2>the following errors prevented the article to be saved</h2>
<% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg|%>
    <ul>
        <li><%= msg %></li>
    </ul>
    <% end %>
<% end %>

<%= form_with scope: :article, url:articles_path, local:true  do |f| %>

    <p>
        <%= f.label :title %></br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description %></br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>

<% end %>

<%= link_to "Back to article listing", articles_path %>

app/views/articles/show.html.erb
<div id="page-content">

<h1>Article show page</h1>
<div class="container card-width ">

<div class="card text-center mb-4">

  <div class="card-header">
    by <%= @article.user.username if @article.user %>
  </div>
  <div class="card-body">
 
    <h5 class="card-title "><%= @article.title %></h5>
    <p class="card-text"><%= @article.description %></p>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
    <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
    
  </div>
  <div class="card-footer text-muted ">
   <p> Created: <%= time_ago_in_words(@article.created_at) %> ago  Updated: <%= time_ago_in_words(@article.updated_at) %> ago</p>
   
  </div>
 
</div>

</div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small bg-dark fixed-bottom">

  <!-- Copyright -->
  <div class="footer-copyright text-center text-white py-3">© 2020 Copyright:
    
    <%= link_to "Alphablog.com", root_path %>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  
  <%= link_to "AlphaBlog",root_path,class:"navbar-brand  nav-link" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        
        <%= link_to "Articles",articles_path, class:" nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Users",users_path, class:" nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-color" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item " href="#">Action</a>
          <%= link_to "Create Article",new_article_path, class:" dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item " href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled " href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <% if session[:user_id]!=nil %>
    <%= link_to "Logout",logout_path, class:" nav-link btn btn-danger mr-3" %>
    <% else %>
    <%= link_to "Login",login_path, class:" nav-link btn btn-success mr-3" %>
    <% end %>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AplhablogTestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="page-content">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
   
    <%= yield %>
  
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>welcome to about page</h1>

<%= link_to "article listing", articles_path %>
<%= link_to "home Page",root_path %>

app/views/pages/home.html.erb
<div class="container">
    <div class="jumbotron mt-4">
    <h1 class="display-4">AlphaBlog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <div class="d-flex justify-content-center">
    <%= link_to "Signup", new_user_path, class:"btn btn-success btn-lg mt-4" %>
    </div>
    </div>
</div>

app/views/users/_form.html.erb
<div class="row justify-content-center">
<div class="col-10">
<% if @user.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved</h4>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> 
  <%= form_with(model: @user, class: "shadow p-3 mt-4 mb-3 bg-info rounded", local: true) do |f| %>
    <div class="form-group row">
      <%= f.label :username, class: "col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "username" %>
      </div>
    </div>
    <div class="form-group row">
    <%= f.label :email, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :email, class: "form-control shadow rounded", placeholder: "user email" %>
    </div>
  </div>
  <div class="form-group row">
  <%= f.label :password, class: "col-2 col-form-label text-light" %>
  <div class="col-10">
    <%= f.text_field :password, class: "form-control shadow rounded", placeholder: "password" %>
  </div>
</div>
   
  <div class="form-group row justify-content-center">
  <%= f.submit (@user.new_record? ? "Sign up" : "Update account"), class: "btn btn-outline-light btn-lg" %>
</div>
<% end %>
</div>
<%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
</div>
</div> 

app/views/users/edit.html.erb
<div id="page-content">
<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container card-width ">
<% @users.each do |user| %>
<div class="card text-center mb-4">

  <div class="card-header">
    username <%= user.username if user %>
  </div>
  <div class="card-body">
 
    <h5 class="card-title "><%= user.email %></h5>
    
    <p class="card-text"><%= user.articles.count %> articles</p>
    <%= link_to "View", user_path(user), class: "btn btn-outline-success" %>
    <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-info" %>
    
    
  </div>
  <div class="card-footer text-muted ">
   <p> Created: <%= time_ago_in_words(user.created_at) %> ago  Updated: <%= time_ago_in_words(user.updated_at) %> ago</p>
   
  </div>
 
</div>
<% end %>

app/views/users/new.html.erb
<div id="page-content">
<h2>create user</h2>

<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div id="page-content">
<div class="div text-center">
<h1><%= @user.username %><h1>
<h3>Associated articles</h3>
</div>

<%= gravatar_for @user, size: 200 %>
<%= render 'articles/list' %>

</div>
</div>